services:
  - type: web
    name: next-happen-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: nexthappen
      - key: Jwt__Audience
        value: nexthappen-users
